package global

import "github.com/ensoria/faker/pkg/faker/provider"

func CreateFiles() *provider.Files {
	return &provider.Files{
		MIMEEntries: MIMEEntries,
	}
}

// MIME types from the apache.org file. Some types are truncated.
// See http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
var MIMEEntries = []*provider.MIMEEntry{
	{"application/atom+xml", []string{"atom"}},
	{"application/ecmascript", []string{"ecma"}},
	{"application/emma+xml", []string{"emma"}},
	{"application/epub+zip", []string{"epub"}},
	{"application/java-archive", []string{"jar"}},
	{"application/java-vm", []string{"class"}},
	{"application/javascript", []string{"js"}},
	{"application/json", []string{"json"}},
	{"application/jsonml+json", []string{"jsonml"}},
	{"application/lost+xml", []string{"lostxml"}},
	{"application/mathml+xml", []string{"mathml"}},
	{"application/mets+xml", []string{"mets"}},
	{"application/mods+xml", []string{"mods"}},
	{"application/mp4", []string{"mp4s"}},
	{"application/msword", []string{"doc", "dot"}},
	{"application/octet-stream", []string{"bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy"}},
	{"application/ogg", []string{"ogx"}},
	{"application/omdoc+xml", []string{"omdoc"}},
	{"application/pdf", []string{"pdf"}},
	{"application/pgp-encrypted", []string{"pgp"}},
	{"application/pgp-signature", []string{"asc", "sig"}},
	{"application/pkix-pkipath", []string{"pkipath"}},
	{"application/pkixcmp", []string{"pki"}},
	{"application/pls+xml", []string{"pls"}},
	{"application/postscript", []string{"ai", "eps", "ps"}},
	{"application/pskc+xml", []string{"pskcxml"}},
	{"application/rdf+xml", []string{"rdf"}},
	{"application/reginfo+xml", []string{"rif"}},
	{"application/rss+xml", []string{"rss"}},
	{"application/rtf", []string{"rtf"}},
	{"application/sbml+xml", []string{"sbml"}},
	{"application/vnd.adobe.air-application-installer-package+zip", []string{"air"}},
	{"application/vnd.adobe.xdp+xml", []string{"xdp"}},
	{"application/vnd.adobe.xfdf", []string{"xfdf"}},
	{"application/vnd.ahead.space", []string{"ahead"}},
	{"application/vnd.dart", []string{"dart"}},
	{"application/vnd.data-vision.rdz", []string{"rdz"}},
	{"application/vnd.dece.data", []string{"uvf", "uvvf", "uvd", "uvvd"}},
	{"application/vnd.dece.ttml+xml", []string{"uvt", "uvvt"}},
	{"application/vnd.dece.unspecified", []string{"uvx", "uvvx"}},
	{"application/vnd.dece.zip", []string{"uvz", "uvvz"}},
	{"application/vnd.denovo.fcselayout-link", []string{"fe_launch"}},
	{"application/vnd.dna", []string{"dna"}},
	{"application/vnd.dolby.mlp", []string{"mlp"}},
	{"application/vnd.dpgraph", []string{"dpg"}},
	{"application/vnd.dreamfactory", []string{"dfac"}},
	{"application/vnd.ds-keypoint", []string{"kpxx"}},
	{"application/vnd.dvb.ait", []string{"ait"}},
	{"application/vnd.dvb.service", []string{"svc"}},
	{"application/vnd.dynageo", []string{"geo"}},
	{"application/vnd.ecowin.chart", []string{"mag"}},
	{"application/vnd.enliven", []string{"nml"}},
	{"application/vnd.epson.esf", []string{"esf"}},
	{"application/vnd.epson.msf", []string{"msf"}},
	{"application/vnd.epson.quickanime", []string{"qam"}},
	{"application/vnd.epson.salt", []string{"slt"}},
	{"application/vnd.epson.ssf", []string{"ssf"}},
	{"application/vnd.ezpix-album", []string{"ez2"}},
	{"application/vnd.ezpix-package", []string{"ez3"}},
	{"application/vnd.fdf", []string{"fdf"}},
	{"application/vnd.fdsn.mseed", []string{"mseed"}},
	{"application/vnd.fdsn.seed", []string{"seed", "dataless"}},
	{"application/vnd.flographit", []string{"gph"}},
	{"application/vnd.fluxtime.clip", []string{"ftc"}},
	{"application/vnd.hal+xml", []string{"hal"}},
	{"application/vnd.hydrostatix.sof-data", []string{"sfd-hdstx"}},
	{"application/vnd.ibm.minipay", []string{"mpy"}},
	{"application/vnd.ibm.secure-container", []string{"sc"}},
	{"application/vnd.iccprofile", []string{"icc", "icm"}},
	{"application/vnd.igloader", []string{"igl"}},
	{"application/vnd.immervision-ivp", []string{"ivp"}},
	{"application/vnd.kde.karbon", []string{"karbon"}},
	{"application/vnd.kde.kchart", []string{"chrt"}},
	{"application/vnd.kde.kformula", []string{"kfo"}},
	{"application/vnd.kde.kivio", []string{"flw"}},
	{"application/vnd.kde.kontour", []string{"kon"}},
	{"application/vnd.kde.kpresenter", []string{"kpr", "kpt"}},
	{"application/vnd.kde.kspread", []string{"ksp"}},
	{"application/vnd.kde.kword", []string{"kwd", "kwt"}},
	{"application/vnd.kenameaapp", []string{"htke"}},
	{"application/vnd.kidspiration", []string{"kia"}},
	{"application/vnd.kinar", []string{"kne", "knp"}},
	{"application/vnd.koan", []string{"skp", "skd", "skt", "skm"}},
	{"application/vnd.kodak-descriptor", []string{"sse"}},
	{"application/vnd.las.las+xml", []string{"lasxml"}},
	{"application/vnd.llamagraphics.life-balance.desktop", []string{"lbd"}},
	{"application/vnd.llamagraphics.life-balance.exchange+xml", []string{"lbe"}},
	{"application/vnd.lotus-1-2-3", []string{"123"}},
	{"application/vnd.lotus-approach", []string{"apr"}},
	{"application/vnd.lotus-freelance", []string{"pre"}},
	{"application/vnd.lotus-notes", []string{"nsf"}},
	{"application/vnd.lotus-organizer", []string{"org"}},
	{"application/vnd.lotus-screencam", []string{"scm"}},
	{"application/vnd.mozilla.xul+xml", []string{"xul"}},
	{"application/vnd.ms-artgalry", []string{"cil"}},
	{"application/vnd.ms-cab-compressed", []string{"cab"}},
	{"application/vnd.ms-excel", []string{"xls", "xlm", "xla", "xlc", "xlt", "xlw"}},
	{"application/vnd.ms-excel.addin.macroenabled.12", []string{"xlam"}},
	{"application/vnd.ms-excel.sheet.binary.macroenabled.12", []string{"xlsb"}},
	{"application/vnd.ms-excel.sheet.macroenabled.12", []string{"xlsm"}},
	{"application/vnd.ms-excel.template.macroenabled.12", []string{"xltm"}},
	{"application/vnd.ms-fontobject", []string{"eot"}},
	{"application/vnd.ms-htmlhelp", []string{"chm"}},
	{"application/vnd.ms-ims", []string{"ims"}},
	{"application/vnd.ms-lrm", []string{"lrm"}},
	{"application/vnd.ms-officetheme", []string{"thmx"}},
	{"application/vnd.ms-pki.seccat", []string{"cat"}},
	{"application/vnd.ms-pki.stl", []string{"stl"}},
	{"application/vnd.ms-powerpoint", []string{"ppt", "pps", "pot"}},
	{"application/vnd.ms-powerpoint.addin.macroenabled.12", []string{"ppam"}},
	{"application/vnd.ms-powerpoint.presentation.macroenabled.12", []string{"pptm"}},
	{"application/vnd.ms-powerpoint.slide.macroenabled.12", []string{"sldm"}},
	{"application/vnd.ms-powerpoint.slideshow.macroenabled.12", []string{"ppsm"}},
	{"application/vnd.ms-powerpoint.template.macroenabled.12", []string{"potm"}},
	{"application/vnd.ms-project", []string{"mpp", "mpt"}},
	{"application/vnd.ms-word.document.macroenabled.12", []string{"docm"}},
	{"application/vnd.ms-word.template.macroenabled.12", []string{"dotm"}},
	{"application/vnd.ms-works", []string{"wps", "wks", "wcm", "wdb"}},
	{"application/vnd.ms-wpl", []string{"wpl"}},
	{"application/vnd.ms-xpsdocument", []string{"xps"}},
	{"application/vnd.mseq", []string{"mseq"}},
	{"application/vnd.musician", []string{"mus"}},
	{"application/vnd.oasis.opendocument.chart", []string{"odc"}},
	{"application/vnd.oasis.opendocument.chart-template", []string{"otc"}},
	{"application/vnd.oasis.opendocument.database", []string{"odb"}},
	{"application/vnd.oasis.opendocument.formula", []string{"odf"}},
	{"application/vnd.oasis.opendocument.formula-template", []string{"odft"}},
	{"application/vnd.oasis.opendocument.graphics", []string{"odg"}},
	{"application/vnd.oasis.opendocument.graphics-template", []string{"otg"}},
	{"application/vnd.oasis.opendocument.image", []string{"odi"}},
	{"application/vnd.oasis.opendocument.image-template", []string{"oti"}},
	{"application/vnd.oasis.opendocument.presentation", []string{"odp"}},
	{"application/vnd.oasis.opendocument.presentation-template", []string{"otp"}},
	{"application/vnd.oasis.opendocument.spreadsheet", []string{"ods"}},
	{"application/vnd.oasis.opendocument.spreadsheet-template", []string{"ots"}},
	{"application/vnd.oasis.opendocument.text", []string{"odt"}},
	{"application/vnd.oasis.opendocument.text-master", []string{"odm"}},
	{"application/vnd.oasis.opendocument.text-template", []string{"ott"}},
	{"application/vnd.oasis.opendocument.text-web", []string{"oth"}},
	{"application/vnd.olpc-sugar", []string{"xo"}},
	{"application/vnd.oma.dd2+xml", []string{"dd2"}},
	{"application/vnd.openofficeorg.extension", []string{"oxt"}},
	{"application/vnd.openxmlformats-officedocument.presentationml.presentation", []string{"pptx"}},
	{"application/vnd.openxmlformats-officedocument.presentationml.slide", []string{"sldx"}},
	{"application/vnd.openxmlformats-officedocument.presentationml.slideshow", []string{"ppsx"}},
	{"application/vnd.openxmlformats-officedocument.presentationml.template", []string{"potx"}},
	{"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", []string{"xlsx"}},
	{"application/vnd.openxmlformats-officedocument.spreadsheetml.template", []string{"xltx"}},
	{"application/vnd.openxmlformats-officedocument.wordprocessingml.document", []string{"docx"}},
	{"application/vnd.openxmlformats-officedocument.wordprocessingml.template", []string{"dotx"}},
	{"application/vnd.pvi.ptid1", []string{"ptid"}},
	{"application/vnd.quark.quarkxpress", []string{"qxd", "qxt", "qwd", "qwt", "qxl", "qxb"}},
	{"application/vnd.realvnc.bed", []string{"bed"}},
	{"application/vnd.recordare.musicxml", []string{"mxl"}},
	{"application/vnd.recordare.musicxml+xml", []string{"musicxml"}},
	{"application/vnd.rig.cryptonote", []string{"cryptonote"}},
	{"application/vnd.rim.cod", []string{"cod"}},
	{"application/vnd.rn-realmedia", []string{"rm"}},
	{"application/vnd.rn-realmedia-vbr", []string{"rmvb"}},
	{"application/vnd.route66.link66+xml", []string{"link66"}},
	{"application/vnd.sailingtracker.track", []string{"st"}},
	{"application/vnd.seemail", []string{"see"}},
	{"application/vnd.sema", []string{"sema"}},
	{"application/vnd.semd", []string{"semd"}},
	{"application/vnd.semf", []string{"semf"}},
	{"application/vnd.shana.informed.formdata", []string{"ifm"}},
	{"application/vnd.shana.informed.formtemplate", []string{"itp"}},
	{"application/vnd.shana.informed.interchange", []string{"iif"}},
	{"application/vnd.shana.informed.package", []string{"ipk"}},
	{"application/vnd.simtech-mindmapper", []string{"twd", "twds"}},
	{"application/vnd.smaf", []string{"mmf"}},
	{"application/vnd.stepmania.stepchart", []string{"sm"}},
	{"application/vnd.sun.xml.calc", []string{"sxc"}},
	{"application/vnd.sun.xml.calc.template", []string{"stc"}},
	{"application/vnd.sun.xml.draw", []string{"sxd"}},
	{"application/vnd.sun.xml.draw.template", []string{"std"}},
	{"application/vnd.sun.xml.impress", []string{"sxi"}},
	{"application/vnd.sun.xml.impress.template", []string{"sti"}},
	{"application/vnd.sun.xml.math", []string{"sxm"}},
	{"application/vnd.sun.xml.writer", []string{"sxw"}},
	{"application/vnd.sun.xml.writer.global", []string{"sxg"}},
	{"application/vnd.sun.xml.writer.template", []string{"stw"}},
	{"application/vnd.sus-calendar", []string{"sus", "susp"}},
	{"application/vnd.svd", []string{"svd"}},
	{"application/vnd.symbian.install", []string{"sis", "sisx"}},
	{"application/vnd.syncml+xml", []string{"xsm"}},
	{"application/vnd.syncml.dm+wbxml", []string{"bdm"}},
	{"application/vnd.syncml.dm+xml", []string{"xdm"}},
	{"application/vnd.tao.intent-module-archive", []string{"tao"}},
	{"application/vnd.tcpdump.pcap", []string{"pcap", "cap", "dmp"}},
	{"application/vnd.tmobile-livetv", []string{"tmo"}},
	{"application/vnd.trid.tpt", []string{"tpt"}},
	{"application/vnd.triscape.mxs", []string{"mxs"}},
	{"application/vnd.trueapp", []string{"tra"}},
	{"application/vnd.ufdl", []string{"ufd", "ufdl"}},
	{"application/vnd.uiq.theme", []string{"utz"}},
	{"application/vnd.umajin", []string{"umj"}},
	{"application/vnd.unity", []string{"unityweb"}},
	{"application/vnd.uoml+xml", []string{"uoml"}},
	{"application/vnd.vcx", []string{"vcx"}},
	{"application/vnd.visio", []string{"vsd", "vst", "vss", "vsw"}},
	{"application/vnd.visionary", []string{"vis"}},
	{"application/vnd.vsf", []string{"vsf"}},
	{"application/vnd.wap.wbxml", []string{"wbxml"}},
	{"application/vnd.wap.wmlc", []string{"wmlc"}},
	{"application/vnd.wap.wmlscriptc", []string{"wmlsc"}},
	{"application/vnd.webturbo", []string{"wtb"}},
	{"application/vnd.wolfram.player", []string{"nbp"}},
	{"application/vnd.wordperfect", []string{"wpd"}},
	{"application/vnd.wqd", []string{"wqd"}},
	{"application/vnd.wt.stf", []string{"stf"}},
	{"application/vnd.xara", []string{"xar"}},
	{"application/vnd.xfdl", []string{"xfdl"}},
	{"application/voicexml+xml", []string{"vxml"}},
	{"application/widget", []string{"wgt"}},
	{"application/winhlp", []string{"hlp"}},
	{"application/wsdl+xml", []string{"wsdl"}},
	{"application/wspolicy+xml", []string{"wspolicy"}},
	{"application/x-7z-compressed", []string{"7z"}},
	{"application/x-bittorrent", []string{"torrent"}},
	{"application/x-blorb", []string{"blb", "blorb"}},
	{"application/x-bzip", []string{"bz"}},
	{"application/x-cdlink", []string{"vcd"}},
	{"application/x-cfs-compressed", []string{"cfs"}},
	{"application/x-chat", []string{"chat"}},
	{"application/x-chess-pgn", []string{"pgn"}},
	{"application/x-conference", []string{"nsc"}},
	{"application/x-cpio", []string{"cpio"}},
	{"application/x-csh", []string{"csh"}},
	{"application/x-debian-package", []string{"deb", "udeb"}},
	{"application/x-dgc-compressed", []string{"dgc"}},
	{"application/x-director", []string{"dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"}},
	{"application/x-font-ttf", []string{"ttf", "ttc"}},
	{"application/x-font-type1", []string{"pfa", "pfb", "pfm", "afm"}},
	{"application/x-font-woff", []string{"woff"}},
	{"application/x-freearc", []string{"arc"}},
	{"application/x-futuresplash", []string{"spl"}},
	{"application/x-gca-compressed", []string{"gca"}},
	{"application/x-glulx", []string{"ulx"}},
	{"application/x-gnumeric", []string{"gnumeric"}},
	{"application/x-gramps-xml", []string{"gramps"}},
	{"application/x-gtar", []string{"gtar"}},
	{"application/x-hdf", []string{"hdf"}},
	{"application/x-install-instructions", []string{"install"}},
	{"application/x-iso9660-image", []string{"iso"}},
	{"application/x-java-jnlp-file", []string{"jnlp"}},
	{"application/x-latex", []string{"latex"}},
	{"application/x-lzh-compressed", []string{"lzh", "lha"}},
	{"application/x-mie", []string{"mie"}},
	{"application/x-mobipocket-ebook", []string{"prc", "mobi"}},
	{"application/x-ms-application", []string{"application"}},
	{"application/x-ms-shortcut", []string{"lnk"}},
	{"application/x-ms-wmd", []string{"wmd"}},
	{"application/x-ms-wmz", []string{"wmz"}},
	{"application/x-ms-xbap", []string{"xbap"}},
	{"application/x-msaccess", []string{"mdb"}},
	{"application/x-msbinder", []string{"obd"}},
	{"application/x-mscardfile", []string{"crd"}},
	{"application/x-msclip", []string{"clp"}},
	{"application/x-msdownload", []string{"exe", "dll", "com", "bat", "msi"}},
	{"application/x-msmediaview", []string{"mvb", "m13", "m14"}},
	{"application/x-msmetafile", []string{"wmf", "wmz", "emf", "emz"}},
	{"application/x-rar-compressed", []string{"rar"}},
	{"application/x-research-info-systems", []string{"ris"}},
	{"application/x-sh", []string{"sh"}},
	{"application/x-shar", []string{"shar"}},
	{"application/x-shockwave-flash", []string{"swf"}},
	{"application/x-silverlight-app", []string{"xap"}},
	{"application/x-sql", []string{"sql"}},
	{"application/x-stuffit", []string{"sit"}},
	{"application/x-stuffitx", []string{"sitx"}},
	{"application/x-subrip", []string{"srt"}},
	{"application/x-sv4cpio", []string{"sv4cpio"}},
	{"application/x-sv4crc", []string{"sv4crc"}},
	{"application/x-t3vm-image", []string{"t3"}},
	{"application/x-tads", []string{"gam"}},
	{"application/x-tar", []string{"tar"}},
	{"application/x-tcl", []string{"tcl"}},
	{"application/x-tex", []string{"tex"}},
	{"application/x-tex-tfm", []string{"tfm"}},
	{"application/x-texinfo", []string{"texinfo", "texi"}},
	{"application/x-tgif", []string{"obj"}},
	{"application/x-ustar", []string{"ustar"}},
	{"application/x-wais-source", []string{"src"}},
	{"application/x-x509-ca-cert", []string{"der", "crt"}},
	{"application/x-xfig", []string{"fig"}},
	{"application/x-xliff+xml", []string{"xlf"}},
	{"application/x-xpinstall", []string{"xpi"}},
	{"application/x-xz", []string{"xz"}},
	{"application/x-zmachine", []string{"z1"}},
	{"application/xaml+xml", []string{"xaml"}},
	{"application/xcap-diff+xml", []string{"xdf"}},
	{"application/xenc+xml", []string{"xenc"}},
	{"application/xhtml+xml", []string{"xhtml", "xht"}},
	{"application/xml", []string{"xml", "xsl"}},
	{"application/xml-dtd", []string{"dtd"}},
	{"application/xop+xml", []string{"xop"}},
	{"application/xproc+xml", []string{"xpl"}},
	{"application/xslt+xml", []string{"xslt"}},
	{"application/xspf+xml", []string{"xspf"}},
	{"application/xv+xml", []string{"mxml", "xhvml", "xvml", "xvm"}},
	{"application/yang", []string{"yang"}},
	{"application/yin+xml", []string{"yin"}},
	{"application/zip", []string{"zip"}},
	{"audio/adpcm", []string{"adp"}},
	{"audio/basic", []string{"au", "snd"}},
	{"audio/midi", []string{"mid", "midi", "kar", "rmi"}},
	{"audio/mp4", []string{"mp4a"}},
	{"audio/mpeg", []string{"mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"}},
	{"audio/ogg", []string{"oga", "ogg", "spx"}},
	{"audio/vnd.dece.audio", []string{"uva", "uvva"}},
	{"audio/vnd.rip", []string{"rip"}},
	{"audio/webm", []string{"weba"}},
	{"audio/x-aac", []string{"aac"}},
	{"audio/x-aiff", []string{"aif", "aiff", "aifc"}},
	{"audio/x-caf", []string{"caf"}},
	{"audio/x-flac", []string{"flac"}},
	{"audio/x-matroska", []string{"mka"}},
	{"audio/x-mpegurl", []string{"m3u"}},
	{"audio/x-ms-wax", []string{"wax"}},
	{"audio/x-ms-wma", []string{"wma"}},
	{"audio/x-pn-realaudio", []string{"ram", "ra"}},
	{"audio/x-pn-realaudio-plugin", []string{"rmp"}},
	{"audio/x-wav", []string{"wav"}},
	{"audio/xm", []string{"xm"}},
	{"image/bmp", []string{"bmp"}},
	{"image/cgm", []string{"cgm"}},
	{"image/g3fax", []string{"g3"}},
	{"image/gif", []string{"gif"}},
	{"image/ief", []string{"ief"}},
	{"image/jpeg", []string{"jpeg", "jpg", "jpe"}},
	{"image/ktx", []string{"ktx"}},
	{"image/png", []string{"png"}},
	{"image/prs.btif", []string{"btif"}},
	{"image/sgi", []string{"sgi"}},
	{"image/svg+xml", []string{"svg", "svgz"}},
	{"image/tiff", []string{"tiff", "tif"}},
	{"image/vnd.adobe.photoshop", []string{"psd"}},
	{"image/vnd.dece.graphic", []string{"uvi", "uvvi", "uvg", "uvvg"}},
	{"image/vnd.dvb.subtitle", []string{"sub"}},
	{"image/vnd.djvu", []string{"djvu", "djv"}},
	{"image/vnd.dwg", []string{"dwg"}},
	{"image/vnd.dxf", []string{"dxf"}},
	{"image/vnd.fastbidsheet", []string{"fbs"}},
	{"image/vnd.fpx", []string{"fpx"}},
	{"image/vnd.fst", []string{"fst"}},
	{"image/vnd.fujixerox.edmics-mmr", []string{"mmr"}},
	{"image/vnd.fujixerox.edmics-rlc", []string{"rlc"}},
	{"image/vnd.ms-modi", []string{"mdi"}},
	{"image/vnd.ms-photo", []string{"wdp"}},
	{"image/vnd.net-fpx", []string{"npx"}},
	{"image/vnd.wap.wbmp", []string{"wbmp"}},
	{"image/vnd.xiff", []string{"xif"}},
	{"image/webp", []string{"webp"}},
	{"image/x-3ds", []string{"3ds"}},
	{"image/x-cmu-raster", []string{"ras"}},
	{"image/x-cmx", []string{"cmx"}},
	{"image/x-freehand", []string{"fh", "fhc", "fh4", "fh5", "fh7"}},
	{"image/x-icon", []string{"ico"}},
	{"image/x-mrsid-image", []string{"sid"}},
	{"image/x-pcx", []string{"pcx"}},
	{"image/x-pict", []string{"pic", "pct"}},
	{"image/x-portable-anymap", []string{"pnm"}},
	{"image/x-portable-bitmap", []string{"pbm"}},
	{"image/x-portable-graymap", []string{"pgm"}},
	{"image/x-portable-pixmap", []string{"ppm"}},
	{"image/x-rgb", []string{"rgb"}},
	{"image/x-tga", []string{"tga"}},
	{"image/x-xbitmap", []string{"xbm"}},
	{"image/x-xpixmap", []string{"xpm"}},
	{"image/x-xwindowdump", []string{"xwd"}},
	{"message/rfc822", []string{"eml", "mime"}},
	{"model/iges", []string{"igs", "iges"}},
	{"model/mesh", []string{"msh", "mesh", "silo"}},
	{"model/vnd.collada+xml", []string{"dae"}},
	{"model/vnd.dwf", []string{"dwf"}},
	{"model/vnd.gdl", []string{"gdl"}},
	{"model/vnd.gtw", []string{"gtw"}},
	{"model/vnd.mts", []string{"mts"}},
	{"model/vnd.vtu", []string{"vtu"}},
	{"model/vrml", []string{"wrl", "vrml"}},
	{"model/x3d+binary", []string{"x3db"}},
	{"model/x3d+vrml", []string{"x3dv"}},
	{"model/x3d+xml", []string{"x3d"}},
	{"text/cache-manifest", []string{"appcache"}},
	{"text/calendar", []string{"ics", "ifb"}},
	{"text/css", []string{"css"}},
	{"text/csv", []string{"csv"}},
	{"text/html", []string{"html", "htm"}},
	{"text/n3", []string{"n3"}},
	{"text/plain", []string{"txt", "text", "conf", "def", "list", "log", "in"}},
	{"text/prs.lines.tag", []string{"dsc"}},
	{"text/richtext", []string{"rtx"}},
	{"text/sgml", []string{"sgml", "sgm"}},
	{"text/tab-separated-values", []string{"tsv"}},
	{"text/troff", []string{"t", "tr", "roff", "man", "me", "ms"}},
	{"text/turtle", []string{"ttl"}},
	{"text/uri-list", []string{"uri", "uris", "urls"}},
	{"text/vcard", []string{"vcard"}},
	{"text/vnd.curl", []string{"curl"}},
	{"text/vnd.curl.dcurl", []string{"dcurl"}},
	{"text/vnd.curl.scurl", []string{"scurl"}},
	{"text/vnd.curl.mcurl", []string{"mcurl"}},
	{"text/vnd.dvb.subtitle", []string{"sub"}},
	{"text/vnd.fly", []string{"fly"}},
	{"text/vnd.fmi.flexstor", []string{"flx"}},
	{"text/vnd.graphviz", []string{"gv"}},
	{"text/vnd.in3d.3dml", []string{"3dml"}},
	{"text/vnd.in3d.spot", []string{"spot"}},
	{"text/vnd.sun.j2me.app-descriptor", []string{"jad"}},
	{"text/vnd.wap.wml", []string{"wml"}},
	{"text/vnd.wap.wmlscript", []string{"wmls"}},
	{"text/x-asm", []string{"s", "asm"}},
	{"text/x-fortran", []string{"f", "for", "f77", "f90"}},
	{"text/x-java-source", []string{"java"}},
	{"text/x-opml", []string{"opml"}},
	{"text/x-pascal", []string{"p", "pas"}},
	{"text/x-nfo", []string{"nfo"}},
	{"text/x-setext", []string{"etx"}},
	{"text/x-sfv", []string{"sfv"}},
	{"text/x-uuencode", []string{"uu"}},
	{"text/x-vcalendar", []string{"vcs"}},
	{"text/x-vcard", []string{"vcf"}},
	{"video/3gpp", []string{"3gp"}},
	{"video/3gpp2", []string{"3g2"}},
	{"video/h261", []string{"h261"}},
	{"video/h263", []string{"h263"}},
	{"video/h264", []string{"h264"}},
	{"video/jpeg", []string{"jpgv"}},
	{"video/jpm", []string{"jpm", "jpgm"}},
	{"video/mj2", []string{"mj2"}},
	{"video/mp4", []string{"mp4"}},
	{"video/mpeg", []string{"mpeg", "mpg", "mpe", "m1v", "m2v"}},
	{"video/ogg", []string{"ogv"}},
	{"video/quicktime", []string{"qt", "mov"}},
	{"video/vnd.dece.hd", []string{"uvh", "uvvh"}},
	{"video/vnd.dece.mobile", []string{"uvm", "uvvm"}},
	{"video/vnd.dece.pd", []string{"uvp", "uvvp"}},
	{"video/vnd.dece.sd", []string{"uvs", "uvvs"}},
	{"video/vnd.dece.video", []string{"uvv", "uvvv"}},
	{"video/vnd.dvb.file", []string{"dvb"}},
	{"video/vnd.fvt", []string{"fvt"}},
	{"video/vnd.mpegurl", []string{"mxu", "m4u"}},
	{"video/vnd.ms-playready.media.pyv", []string{"pyv"}},
	{"video/vnd.uvvu.mp4", []string{"uvu", "uvvu"}},
	{"video/vnd.vivo", []string{"viv"}},
	{"video/webm", []string{"webm"}},
	{"video/x-f4v", []string{"f4v"}},
	{"video/x-fli", []string{"fli"}},
	{"video/x-flv", []string{"flv"}},
	{"video/x-m4v", []string{"m4v"}},
	{"video/x-matroska", []string{"mkv", "mk3d", "mks"}},
	{"video/x-mng", []string{"mng"}},
	{"video/x-ms-asf", []string{"asf", "asx"}},
	{"video/x-ms-vob", []string{"vob"}},
	{"video/x-ms-wm", []string{"wm"}},
	{"video/x-ms-wmv", []string{"wmv"}},
	{"video/x-ms-wmx", []string{"wmx"}},
	{"video/x-ms-wvx", []string{"wvx"}},
	{"video/x-msvideo", []string{"avi"}},
	{"video/x-sgi-movie", []string{"movie"}},
}
