package global

import "github.com/ensoria/faker/pkg/faker/provider"

func CreateFiles() *provider.Files {
	return &provider.Files{
		MIMEEntries: MIMEEntries,
	}
}

// MIME types from the apache.org file. Some types are truncated.
// See http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
var MIMEEntries = []*provider.MIMEEntry{
	{Type: "application/atom+xml", Extensions: []string{"atom"}},
	{Type: "application/ecmascript", Extensions: []string{"ecma"}},
	{Type: "application/emma+xml", Extensions: []string{"emma"}},
	{Type: "application/epub+zip", Extensions: []string{"epub"}},
	{Type: "application/java-archive", Extensions: []string{"jar"}},
	{Type: "application/java-vm", Extensions: []string{"class"}},
	{Type: "application/javascript", Extensions: []string{"js"}},
	{Type: "application/json", Extensions: []string{"json"}},
	{Type: "application/jsonml+json", Extensions: []string{"jsonml"}},
	{Type: "application/lost+xml", Extensions: []string{"lostxml"}},
	{Type: "application/mathml+xml", Extensions: []string{"mathml"}},
	{Type: "application/mets+xml", Extensions: []string{"mets"}},
	{Type: "application/mods+xml", Extensions: []string{"mods"}},
	{Type: "application/mp4", Extensions: []string{"mp4s"}},
	{Type: "application/msword", Extensions: []string{"doc", "dot"}},
	{Type: "application/octet-stream", Extensions: []string{"bin", "dms", "lrf", "mar", "so", "dist", "distz", "pkg", "bpk", "dump", "elc", "deploy"}},
	{Type: "application/ogg", Extensions: []string{"ogx"}},
	{Type: "application/omdoc+xml", Extensions: []string{"omdoc"}},
	{Type: "application/pdf", Extensions: []string{"pdf"}},
	{Type: "application/pgp-encrypted", Extensions: []string{"pgp"}},
	{Type: "application/pgp-signature", Extensions: []string{"asc", "sig"}},
	{Type: "application/pkix-pkipath", Extensions: []string{"pkipath"}},
	{Type: "application/pkixcmp", Extensions: []string{"pki"}},
	{Type: "application/pls+xml", Extensions: []string{"pls"}},
	{Type: "application/postscript", Extensions: []string{"ai", "eps", "ps"}},
	{Type: "application/pskc+xml", Extensions: []string{"pskcxml"}},
	{Type: "application/rdf+xml", Extensions: []string{"rdf"}},
	{Type: "application/reginfo+xml", Extensions: []string{"rif"}},
	{Type: "application/rss+xml", Extensions: []string{"rss"}},
	{Type: "application/rtf", Extensions: []string{"rtf"}},
	{Type: "application/sbml+xml", Extensions: []string{"sbml"}},
	{Type: "application/vnd.adobe.air-application-installer-package+zip", Extensions: []string{"air"}},
	{Type: "application/vnd.adobe.xdp+xml", Extensions: []string{"xdp"}},
	{Type: "application/vnd.adobe.xfdf", Extensions: []string{"xfdf"}},
	{Type: "application/vnd.ahead.space", Extensions: []string{"ahead"}},
	{Type: "application/vnd.dart", Extensions: []string{"dart"}},
	{Type: "application/vnd.data-vision.rdz", Extensions: []string{"rdz"}},
	{Type: "application/vnd.dece.data", Extensions: []string{"uvf", "uvvf", "uvd", "uvvd"}},
	{Type: "application/vnd.dece.ttml+xml", Extensions: []string{"uvt", "uvvt"}},
	{Type: "application/vnd.dece.unspecified", Extensions: []string{"uvx", "uvvx"}},
	{Type: "application/vnd.dece.zip", Extensions: []string{"uvz", "uvvz"}},
	{Type: "application/vnd.denovo.fcselayout-link", Extensions: []string{"fe_launch"}},
	{Type: "application/vnd.dna", Extensions: []string{"dna"}},
	{Type: "application/vnd.dolby.mlp", Extensions: []string{"mlp"}},
	{Type: "application/vnd.dpgraph", Extensions: []string{"dpg"}},
	{Type: "application/vnd.dreamfactory", Extensions: []string{"dfac"}},
	{Type: "application/vnd.ds-keypoint", Extensions: []string{"kpxx"}},
	{Type: "application/vnd.dvb.ait", Extensions: []string{"ait"}},
	{Type: "application/vnd.dvb.service", Extensions: []string{"svc"}},
	{Type: "application/vnd.dynageo", Extensions: []string{"geo"}},
	{Type: "application/vnd.ecowin.chart", Extensions: []string{"mag"}},
	{Type: "application/vnd.enliven", Extensions: []string{"nml"}},
	{Type: "application/vnd.epson.esf", Extensions: []string{"esf"}},
	{Type: "application/vnd.epson.msf", Extensions: []string{"msf"}},
	{Type: "application/vnd.epson.quickanime", Extensions: []string{"qam"}},
	{Type: "application/vnd.epson.salt", Extensions: []string{"slt"}},
	{Type: "application/vnd.epson.ssf", Extensions: []string{"ssf"}},
	{Type: "application/vnd.ezpix-album", Extensions: []string{"ez2"}},
	{Type: "application/vnd.ezpix-package", Extensions: []string{"ez3"}},
	{Type: "application/vnd.fdf", Extensions: []string{"fdf"}},
	{Type: "application/vnd.fdsn.mseed", Extensions: []string{"mseed"}},
	{Type: "application/vnd.fdsn.seed", Extensions: []string{"seed", "dataless"}},
	{Type: "application/vnd.flographit", Extensions: []string{"gph"}},
	{Type: "application/vnd.fluxtime.clip", Extensions: []string{"ftc"}},
	{Type: "application/vnd.hal+xml", Extensions: []string{"hal"}},
	{Type: "application/vnd.hydrostatix.sof-data", Extensions: []string{"sfd-hdstx"}},
	{Type: "application/vnd.ibm.minipay", Extensions: []string{"mpy"}},
	{Type: "application/vnd.ibm.secure-container", Extensions: []string{"sc"}},
	{Type: "application/vnd.iccprofile", Extensions: []string{"icc", "icm"}},
	{Type: "application/vnd.igloader", Extensions: []string{"igl"}},
	{Type: "application/vnd.immervision-ivp", Extensions: []string{"ivp"}},
	{Type: "application/vnd.kde.karbon", Extensions: []string{"karbon"}},
	{Type: "application/vnd.kde.kchart", Extensions: []string{"chrt"}},
	{Type: "application/vnd.kde.kformula", Extensions: []string{"kfo"}},
	{Type: "application/vnd.kde.kivio", Extensions: []string{"flw"}},
	{Type: "application/vnd.kde.kontour", Extensions: []string{"kon"}},
	{Type: "application/vnd.kde.kpresenter", Extensions: []string{"kpr", "kpt"}},
	{Type: "application/vnd.kde.kspread", Extensions: []string{"ksp"}},
	{Type: "application/vnd.kde.kword", Extensions: []string{"kwd", "kwt"}},
	{Type: "application/vnd.kenameaapp", Extensions: []string{"htke"}},
	{Type: "application/vnd.kidspiration", Extensions: []string{"kia"}},
	{Type: "application/vnd.kinar", Extensions: []string{"kne", "knp"}},
	{Type: "application/vnd.koan", Extensions: []string{"skp", "skd", "skt", "skm"}},
	{Type: "application/vnd.kodak-descriptor", Extensions: []string{"sse"}},
	{Type: "application/vnd.las.las+xml", Extensions: []string{"lasxml"}},
	{Type: "application/vnd.llamagraphics.life-balance.desktop", Extensions: []string{"lbd"}},
	{Type: "application/vnd.llamagraphics.life-balance.exchange+xml", Extensions: []string{"lbe"}},
	{Type: "application/vnd.lotus-1-2-3", Extensions: []string{"123"}},
	{Type: "application/vnd.lotus-approach", Extensions: []string{"apr"}},
	{Type: "application/vnd.lotus-freelance", Extensions: []string{"pre"}},
	{Type: "application/vnd.lotus-notes", Extensions: []string{"nsf"}},
	{Type: "application/vnd.lotus-organizer", Extensions: []string{"org"}},
	{Type: "application/vnd.lotus-screencam", Extensions: []string{"scm"}},
	{Type: "application/vnd.mozilla.xul+xml", Extensions: []string{"xul"}},
	{Type: "application/vnd.ms-artgalry", Extensions: []string{"cil"}},
	{Type: "application/vnd.ms-cab-compressed", Extensions: []string{"cab"}},
	{Type: "application/vnd.ms-excel", Extensions: []string{"xls", "xlm", "xla", "xlc", "xlt", "xlw"}},
	{Type: "application/vnd.ms-excel.addin.macroenabled.12", Extensions: []string{"xlam"}},
	{Type: "application/vnd.ms-excel.sheet.binary.macroenabled.12", Extensions: []string{"xlsb"}},
	{Type: "application/vnd.ms-excel.sheet.macroenabled.12", Extensions: []string{"xlsm"}},
	{Type: "application/vnd.ms-excel.template.macroenabled.12", Extensions: []string{"xltm"}},
	{Type: "application/vnd.ms-fontobject", Extensions: []string{"eot"}},
	{Type: "application/vnd.ms-htmlhelp", Extensions: []string{"chm"}},
	{Type: "application/vnd.ms-ims", Extensions: []string{"ims"}},
	{Type: "application/vnd.ms-lrm", Extensions: []string{"lrm"}},
	{Type: "application/vnd.ms-officetheme", Extensions: []string{"thmx"}},
	{Type: "application/vnd.ms-pki.seccat", Extensions: []string{"cat"}},
	{Type: "application/vnd.ms-pki.stl", Extensions: []string{"stl"}},
	{Type: "application/vnd.ms-powerpoint", Extensions: []string{"ppt", "pps", "pot"}},
	{Type: "application/vnd.ms-powerpoint.addin.macroenabled.12", Extensions: []string{"ppam"}},
	{Type: "application/vnd.ms-powerpoint.presentation.macroenabled.12", Extensions: []string{"pptm"}},
	{Type: "application/vnd.ms-powerpoint.slide.macroenabled.12", Extensions: []string{"sldm"}},
	{Type: "application/vnd.ms-powerpoint.slideshow.macroenabled.12", Extensions: []string{"ppsm"}},
	{Type: "application/vnd.ms-powerpoint.template.macroenabled.12", Extensions: []string{"potm"}},
	{Type: "application/vnd.ms-project", Extensions: []string{"mpp", "mpt"}},
	{Type: "application/vnd.ms-word.document.macroenabled.12", Extensions: []string{"docm"}},
	{Type: "application/vnd.ms-word.template.macroenabled.12", Extensions: []string{"dotm"}},
	{Type: "application/vnd.ms-works", Extensions: []string{"wps", "wks", "wcm", "wdb"}},
	{Type: "application/vnd.ms-wpl", Extensions: []string{"wpl"}},
	{Type: "application/vnd.ms-xpsdocument", Extensions: []string{"xps"}},
	{Type: "application/vnd.mseq", Extensions: []string{"mseq"}},
	{Type: "application/vnd.musician", Extensions: []string{"mus"}},
	{Type: "application/vnd.oasis.opendocument.chart", Extensions: []string{"odc"}},
	{Type: "application/vnd.oasis.opendocument.chart-template", Extensions: []string{"otc"}},
	{Type: "application/vnd.oasis.opendocument.database", Extensions: []string{"odb"}},
	{Type: "application/vnd.oasis.opendocument.formula", Extensions: []string{"odf"}},
	{Type: "application/vnd.oasis.opendocument.formula-template", Extensions: []string{"odft"}},
	{Type: "application/vnd.oasis.opendocument.graphics", Extensions: []string{"odg"}},
	{Type: "application/vnd.oasis.opendocument.graphics-template", Extensions: []string{"otg"}},
	{Type: "application/vnd.oasis.opendocument.image", Extensions: []string{"odi"}},
	{Type: "application/vnd.oasis.opendocument.image-template", Extensions: []string{"oti"}},
	{Type: "application/vnd.oasis.opendocument.presentation", Extensions: []string{"odp"}},
	{Type: "application/vnd.oasis.opendocument.presentation-template", Extensions: []string{"otp"}},
	{Type: "application/vnd.oasis.opendocument.spreadsheet", Extensions: []string{"ods"}},
	{Type: "application/vnd.oasis.opendocument.spreadsheet-template", Extensions: []string{"ots"}},
	{Type: "application/vnd.oasis.opendocument.text", Extensions: []string{"odt"}},
	{Type: "application/vnd.oasis.opendocument.text-master", Extensions: []string{"odm"}},
	{Type: "application/vnd.oasis.opendocument.text-template", Extensions: []string{"ott"}},
	{Type: "application/vnd.oasis.opendocument.text-web", Extensions: []string{"oth"}},
	{Type: "application/vnd.olpc-sugar", Extensions: []string{"xo"}},
	{Type: "application/vnd.oma.dd2+xml", Extensions: []string{"dd2"}},
	{Type: "application/vnd.openofficeorg.extension", Extensions: []string{"oxt"}},
	{Type: "application/vnd.openxmlformats-officedocument.presentationml.presentation", Extensions: []string{"pptx"}},
	{Type: "application/vnd.openxmlformats-officedocument.presentationml.slide", Extensions: []string{"sldx"}},
	{Type: "application/vnd.openxmlformats-officedocument.presentationml.slideshow", Extensions: []string{"ppsx"}},
	{Type: "application/vnd.openxmlformats-officedocument.presentationml.template", Extensions: []string{"potx"}},
	{Type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", Extensions: []string{"xlsx"}},
	{Type: "application/vnd.openxmlformats-officedocument.spreadsheetml.template", Extensions: []string{"xltx"}},
	{Type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document", Extensions: []string{"docx"}},
	{Type: "application/vnd.openxmlformats-officedocument.wordprocessingml.template", Extensions: []string{"dotx"}},
	{Type: "application/vnd.pvi.ptid1", Extensions: []string{"ptid"}},
	{Type: "application/vnd.quark.quarkxpress", Extensions: []string{"qxd", "qxt", "qwd", "qwt", "qxl", "qxb"}},
	{Type: "application/vnd.realvnc.bed", Extensions: []string{"bed"}},
	{Type: "application/vnd.recordare.musicxml", Extensions: []string{"mxl"}},
	{Type: "application/vnd.recordare.musicxml+xml", Extensions: []string{"musicxml"}},
	{Type: "application/vnd.rig.cryptonote", Extensions: []string{"cryptonote"}},
	{Type: "application/vnd.rim.cod", Extensions: []string{"cod"}},
	{Type: "application/vnd.rn-realmedia", Extensions: []string{"rm"}},
	{Type: "application/vnd.rn-realmedia-vbr", Extensions: []string{"rmvb"}},
	{Type: "application/vnd.route66.link66+xml", Extensions: []string{"link66"}},
	{Type: "application/vnd.sailingtracker.track", Extensions: []string{"st"}},
	{Type: "application/vnd.seemail", Extensions: []string{"see"}},
	{Type: "application/vnd.sema", Extensions: []string{"sema"}},
	{Type: "application/vnd.semd", Extensions: []string{"semd"}},
	{Type: "application/vnd.semf", Extensions: []string{"semf"}},
	{Type: "application/vnd.shana.informed.formdata", Extensions: []string{"ifm"}},
	{Type: "application/vnd.shana.informed.formtemplate", Extensions: []string{"itp"}},
	{Type: "application/vnd.shana.informed.interchange", Extensions: []string{"iif"}},
	{Type: "application/vnd.shana.informed.package", Extensions: []string{"ipk"}},
	{Type: "application/vnd.simtech-mindmapper", Extensions: []string{"twd", "twds"}},
	{Type: "application/vnd.smaf", Extensions: []string{"mmf"}},
	{Type: "application/vnd.stepmania.stepchart", Extensions: []string{"sm"}},
	{Type: "application/vnd.sun.xml.calc", Extensions: []string{"sxc"}},
	{Type: "application/vnd.sun.xml.calc.template", Extensions: []string{"stc"}},
	{Type: "application/vnd.sun.xml.draw", Extensions: []string{"sxd"}},
	{Type: "application/vnd.sun.xml.draw.template", Extensions: []string{"std"}},
	{Type: "application/vnd.sun.xml.impress", Extensions: []string{"sxi"}},
	{Type: "application/vnd.sun.xml.impress.template", Extensions: []string{"sti"}},
	{Type: "application/vnd.sun.xml.math", Extensions: []string{"sxm"}},
	{Type: "application/vnd.sun.xml.writer", Extensions: []string{"sxw"}},
	{Type: "application/vnd.sun.xml.writer.global", Extensions: []string{"sxg"}},
	{Type: "application/vnd.sun.xml.writer.template", Extensions: []string{"stw"}},
	{Type: "application/vnd.sus-calendar", Extensions: []string{"sus", "susp"}},
	{Type: "application/vnd.svd", Extensions: []string{"svd"}},
	{Type: "application/vnd.symbian.install", Extensions: []string{"sis", "sisx"}},
	{Type: "application/vnd.syncml+xml", Extensions: []string{"xsm"}},
	{Type: "application/vnd.syncml.dm+wbxml", Extensions: []string{"bdm"}},
	{Type: "application/vnd.syncml.dm+xml", Extensions: []string{"xdm"}},
	{Type: "application/vnd.tao.intent-module-archive", Extensions: []string{"tao"}},
	{Type: "application/vnd.tcpdump.pcap", Extensions: []string{"pcap", "cap", "dmp"}},
	{Type: "application/vnd.tmobile-livetv", Extensions: []string{"tmo"}},
	{Type: "application/vnd.trid.tpt", Extensions: []string{"tpt"}},
	{Type: "application/vnd.triscape.mxs", Extensions: []string{"mxs"}},
	{Type: "application/vnd.trueapp", Extensions: []string{"tra"}},
	{Type: "application/vnd.ufdl", Extensions: []string{"ufd", "ufdl"}},
	{Type: "application/vnd.uiq.theme", Extensions: []string{"utz"}},
	{Type: "application/vnd.umajin", Extensions: []string{"umj"}},
	{Type: "application/vnd.unity", Extensions: []string{"unityweb"}},
	{Type: "application/vnd.uoml+xml", Extensions: []string{"uoml"}},
	{Type: "application/vnd.vcx", Extensions: []string{"vcx"}},
	{Type: "application/vnd.visio", Extensions: []string{"vsd", "vst", "vss", "vsw"}},
	{Type: "application/vnd.visionary", Extensions: []string{"vis"}},
	{Type: "application/vnd.vsf", Extensions: []string{"vsf"}},
	{Type: "application/vnd.wap.wbxml", Extensions: []string{"wbxml"}},
	{Type: "application/vnd.wap.wmlc", Extensions: []string{"wmlc"}},
	{Type: "application/vnd.wap.wmlscriptc", Extensions: []string{"wmlsc"}},
	{Type: "application/vnd.webturbo", Extensions: []string{"wtb"}},
	{Type: "application/vnd.wolfram.player", Extensions: []string{"nbp"}},
	{Type: "application/vnd.wordperfect", Extensions: []string{"wpd"}},
	{Type: "application/vnd.wqd", Extensions: []string{"wqd"}},
	{Type: "application/vnd.wt.stf", Extensions: []string{"stf"}},
	{Type: "application/vnd.xara", Extensions: []string{"xar"}},
	{Type: "application/vnd.xfdl", Extensions: []string{"xfdl"}},
	{Type: "application/voicexml+xml", Extensions: []string{"vxml"}},
	{Type: "application/widget", Extensions: []string{"wgt"}},
	{Type: "application/winhlp", Extensions: []string{"hlp"}},
	{Type: "application/wsdl+xml", Extensions: []string{"wsdl"}},
	{Type: "application/wspolicy+xml", Extensions: []string{"wspolicy"}},
	{Type: "application/x-7z-compressed", Extensions: []string{"7z"}},
	{Type: "application/x-bittorrent", Extensions: []string{"torrent"}},
	{Type: "application/x-blorb", Extensions: []string{"blb", "blorb"}},
	{Type: "application/x-bzip", Extensions: []string{"bz"}},
	{Type: "application/x-cdlink", Extensions: []string{"vcd"}},
	{Type: "application/x-cfs-compressed", Extensions: []string{"cfs"}},
	{Type: "application/x-chat", Extensions: []string{"chat"}},
	{Type: "application/x-chess-pgn", Extensions: []string{"pgn"}},
	{Type: "application/x-conference", Extensions: []string{"nsc"}},
	{Type: "application/x-cpio", Extensions: []string{"cpio"}},
	{Type: "application/x-csh", Extensions: []string{"csh"}},
	{Type: "application/x-debian-package", Extensions: []string{"deb", "udeb"}},
	{Type: "application/x-dgc-compressed", Extensions: []string{"dgc"}},
	{Type: "application/x-director", Extensions: []string{"dir", "dcr", "dxr", "cst", "cct", "cxt", "w3d", "fgd", "swa"}},
	{Type: "application/x-font-ttf", Extensions: []string{"ttf", "ttc"}},
	{Type: "application/x-font-type1", Extensions: []string{"pfa", "pfb", "pfm", "afm"}},
	{Type: "application/x-font-woff", Extensions: []string{"woff"}},
	{Type: "application/x-freearc", Extensions: []string{"arc"}},
	{Type: "application/x-futuresplash", Extensions: []string{"spl"}},
	{Type: "application/x-gca-compressed", Extensions: []string{"gca"}},
	{Type: "application/x-glulx", Extensions: []string{"ulx"}},
	{Type: "application/x-gnumeric", Extensions: []string{"gnumeric"}},
	{Type: "application/x-gramps-xml", Extensions: []string{"gramps"}},
	{Type: "application/x-gtar", Extensions: []string{"gtar"}},
	{Type: "application/x-hdf", Extensions: []string{"hdf"}},
	{Type: "application/x-install-instructions", Extensions: []string{"install"}},
	{Type: "application/x-iso9660-image", Extensions: []string{"iso"}},
	{Type: "application/x-java-jnlp-file", Extensions: []string{"jnlp"}},
	{Type: "application/x-latex", Extensions: []string{"latex"}},
	{Type: "application/x-lzh-compressed", Extensions: []string{"lzh", "lha"}},
	{Type: "application/x-mie", Extensions: []string{"mie"}},
	{Type: "application/x-mobipocket-ebook", Extensions: []string{"prc", "mobi"}},
	{Type: "application/x-ms-application", Extensions: []string{"application"}},
	{Type: "application/x-ms-shortcut", Extensions: []string{"lnk"}},
	{Type: "application/x-ms-wmd", Extensions: []string{"wmd"}},
	{Type: "application/x-ms-wmz", Extensions: []string{"wmz"}},
	{Type: "application/x-ms-xbap", Extensions: []string{"xbap"}},
	{Type: "application/x-msaccess", Extensions: []string{"mdb"}},
	{Type: "application/x-msbinder", Extensions: []string{"obd"}},
	{Type: "application/x-mscardfile", Extensions: []string{"crd"}},
	{Type: "application/x-msclip", Extensions: []string{"clp"}},
	{Type: "application/x-msdownload", Extensions: []string{"exe", "dll", "com", "bat", "msi"}},
	{Type: "application/x-msmediaview", Extensions: []string{"mvb", "m13", "m14"}},
	{Type: "application/x-msmetafile", Extensions: []string{"wmf", "wmz", "emf", "emz"}},
	{Type: "application/x-rar-compressed", Extensions: []string{"rar"}},
	{Type: "application/x-research-info-systems", Extensions: []string{"ris"}},
	{Type: "application/x-sh", Extensions: []string{"sh"}},
	{Type: "application/x-shar", Extensions: []string{"shar"}},
	{Type: "application/x-shockwave-flash", Extensions: []string{"swf"}},
	{Type: "application/x-silverlight-app", Extensions: []string{"xap"}},
	{Type: "application/x-sql", Extensions: []string{"sql"}},
	{Type: "application/x-stuffit", Extensions: []string{"sit"}},
	{Type: "application/x-stuffitx", Extensions: []string{"sitx"}},
	{Type: "application/x-subrip", Extensions: []string{"srt"}},
	{Type: "application/x-sv4cpio", Extensions: []string{"sv4cpio"}},
	{Type: "application/x-sv4crc", Extensions: []string{"sv4crc"}},
	{Type: "application/x-t3vm-image", Extensions: []string{"t3"}},
	{Type: "application/x-tads", Extensions: []string{"gam"}},
	{Type: "application/x-tar", Extensions: []string{"tar"}},
	{Type: "application/x-tcl", Extensions: []string{"tcl"}},
	{Type: "application/x-tex", Extensions: []string{"tex"}},
	{Type: "application/x-tex-tfm", Extensions: []string{"tfm"}},
	{Type: "application/x-texinfo", Extensions: []string{"texinfo", "texi"}},
	{Type: "application/x-tgif", Extensions: []string{"obj"}},
	{Type: "application/x-ustar", Extensions: []string{"ustar"}},
	{Type: "application/x-wais-source", Extensions: []string{"src"}},
	{Type: "application/x-x509-ca-cert", Extensions: []string{"der", "crt"}},
	{Type: "application/x-xfig", Extensions: []string{"fig"}},
	{Type: "application/x-xliff+xml", Extensions: []string{"xlf"}},
	{Type: "application/x-xpinstall", Extensions: []string{"xpi"}},
	{Type: "application/x-xz", Extensions: []string{"xz"}},
	{Type: "application/x-zmachine", Extensions: []string{"z1"}},
	{Type: "application/xaml+xml", Extensions: []string{"xaml"}},
	{Type: "application/xcap-diff+xml", Extensions: []string{"xdf"}},
	{Type: "application/xenc+xml", Extensions: []string{"xenc"}},
	{Type: "application/xhtml+xml", Extensions: []string{"xhtml", "xht"}},
	{Type: "application/xml", Extensions: []string{"xml", "xsl"}},
	{Type: "application/xml-dtd", Extensions: []string{"dtd"}},
	{Type: "application/xop+xml", Extensions: []string{"xop"}},
	{Type: "application/xproc+xml", Extensions: []string{"xpl"}},
	{Type: "application/xslt+xml", Extensions: []string{"xslt"}},
	{Type: "application/xspf+xml", Extensions: []string{"xspf"}},
	{Type: "application/xv+xml", Extensions: []string{"mxml", "xhvml", "xvml", "xvm"}},
	{Type: "application/yang", Extensions: []string{"yang"}},
	{Type: "application/yin+xml", Extensions: []string{"yin"}},
	{Type: "application/zip", Extensions: []string{"zip"}},
	{Type: "audio/adpcm", Extensions: []string{"adp"}},
	{Type: "audio/basic", Extensions: []string{"au", "snd"}},
	{Type: "audio/midi", Extensions: []string{"mid", "midi", "kar", "rmi"}},
	{Type: "audio/mp4", Extensions: []string{"mp4a"}},
	{Type: "audio/mpeg", Extensions: []string{"mpga", "mp2", "mp2a", "mp3", "m2a", "m3a"}},
	{Type: "audio/ogg", Extensions: []string{"oga", "ogg", "spx"}},
	{Type: "audio/vnd.dece.audio", Extensions: []string{"uva", "uvva"}},
	{Type: "audio/vnd.rip", Extensions: []string{"rip"}},
	{Type: "audio/webm", Extensions: []string{"weba"}},
	{Type: "audio/x-aac", Extensions: []string{"aac"}},
	{Type: "audio/x-aiff", Extensions: []string{"aif", "aiff", "aifc"}},
	{Type: "audio/x-caf", Extensions: []string{"caf"}},
	{Type: "audio/x-flac", Extensions: []string{"flac"}},
	{Type: "audio/x-matroska", Extensions: []string{"mka"}},
	{Type: "audio/x-mpegurl", Extensions: []string{"m3u"}},
	{Type: "audio/x-ms-wax", Extensions: []string{"wax"}},
	{Type: "audio/x-ms-wma", Extensions: []string{"wma"}},
	{Type: "audio/x-pn-realaudio", Extensions: []string{"ram", "ra"}},
	{Type: "audio/x-pn-realaudio-plugin", Extensions: []string{"rmp"}},
	{Type: "audio/x-wav", Extensions: []string{"wav"}},
	{Type: "audio/xm", Extensions: []string{"xm"}},
	{Type: "image/bmp", Extensions: []string{"bmp"}},
	{Type: "image/cgm", Extensions: []string{"cgm"}},
	{Type: "image/g3fax", Extensions: []string{"g3"}},
	{Type: "image/gif", Extensions: []string{"gif"}},
	{Type: "image/ief", Extensions: []string{"ief"}},
	{Type: "image/jpeg", Extensions: []string{"jpeg", "jpg", "jpe"}},
	{Type: "image/ktx", Extensions: []string{"ktx"}},
	{Type: "image/png", Extensions: []string{"png"}},
	{Type: "image/prs.btif", Extensions: []string{"btif"}},
	{Type: "image/sgi", Extensions: []string{"sgi"}},
	{Type: "image/svg+xml", Extensions: []string{"svg", "svgz"}},
	{Type: "image/tiff", Extensions: []string{"tiff", "tif"}},
	{Type: "image/vnd.adobe.photoshop", Extensions: []string{"psd"}},
	{Type: "image/vnd.dece.graphic", Extensions: []string{"uvi", "uvvi", "uvg", "uvvg"}},
	{Type: "image/vnd.dvb.subtitle", Extensions: []string{"sub"}},
	{Type: "image/vnd.djvu", Extensions: []string{"djvu", "djv"}},
	{Type: "image/vnd.dwg", Extensions: []string{"dwg"}},
	{Type: "image/vnd.dxf", Extensions: []string{"dxf"}},
	{Type: "image/vnd.fastbidsheet", Extensions: []string{"fbs"}},
	{Type: "image/vnd.fpx", Extensions: []string{"fpx"}},
	{Type: "image/vnd.fst", Extensions: []string{"fst"}},
	{Type: "image/vnd.fujixerox.edmics-mmr", Extensions: []string{"mmr"}},
	{Type: "image/vnd.fujixerox.edmics-rlc", Extensions: []string{"rlc"}},
	{Type: "image/vnd.ms-modi", Extensions: []string{"mdi"}},
	{Type: "image/vnd.ms-photo", Extensions: []string{"wdp"}},
	{Type: "image/vnd.net-fpx", Extensions: []string{"npx"}},
	{Type: "image/vnd.wap.wbmp", Extensions: []string{"wbmp"}},
	{Type: "image/vnd.xiff", Extensions: []string{"xif"}},
	{Type: "image/webp", Extensions: []string{"webp"}},
	{Type: "image/x-3ds", Extensions: []string{"3ds"}},
	{Type: "image/x-cmu-raster", Extensions: []string{"ras"}},
	{Type: "image/x-cmx", Extensions: []string{"cmx"}},
	{Type: "image/x-freehand", Extensions: []string{"fh", "fhc", "fh4", "fh5", "fh7"}},
	{Type: "image/x-icon", Extensions: []string{"ico"}},
	{Type: "image/x-mrsid-image", Extensions: []string{"sid"}},
	{Type: "image/x-pcx", Extensions: []string{"pcx"}},
	{Type: "image/x-pict", Extensions: []string{"pic", "pct"}},
	{Type: "image/x-portable-anymap", Extensions: []string{"pnm"}},
	{Type: "image/x-portable-bitmap", Extensions: []string{"pbm"}},
	{Type: "image/x-portable-graymap", Extensions: []string{"pgm"}},
	{Type: "image/x-portable-pixmap", Extensions: []string{"ppm"}},
	{Type: "image/x-rgb", Extensions: []string{"rgb"}},
	{Type: "image/x-tga", Extensions: []string{"tga"}},
	{Type: "image/x-xbitmap", Extensions: []string{"xbm"}},
	{Type: "image/x-xpixmap", Extensions: []string{"xpm"}},
	{Type: "image/x-xwindowdump", Extensions: []string{"xwd"}},
	{Type: "message/rfc822", Extensions: []string{"eml", "mime"}},
	{Type: "model/iges", Extensions: []string{"igs", "iges"}},
	{Type: "model/mesh", Extensions: []string{"msh", "mesh", "silo"}},
	{Type: "model/vnd.collada+xml", Extensions: []string{"dae"}},
	{Type: "model/vnd.dwf", Extensions: []string{"dwf"}},
	{Type: "model/vnd.gdl", Extensions: []string{"gdl"}},
	{Type: "model/vnd.gtw", Extensions: []string{"gtw"}},
	{Type: "model/vnd.mts", Extensions: []string{"mts"}},
	{Type: "model/vnd.vtu", Extensions: []string{"vtu"}},
	{Type: "model/vrml", Extensions: []string{"wrl", "vrml"}},
	{Type: "model/x3d+binary", Extensions: []string{"x3db"}},
	{Type: "model/x3d+vrml", Extensions: []string{"x3dv"}},
	{Type: "model/x3d+xml", Extensions: []string{"x3d"}},
	{Type: "text/cache-manifest", Extensions: []string{"appcache"}},
	{Type: "text/calendar", Extensions: []string{"ics", "ifb"}},
	{Type: "text/css", Extensions: []string{"css"}},
	{Type: "text/csv", Extensions: []string{"csv"}},
	{Type: "text/html", Extensions: []string{"html", "htm"}},
	{Type: "text/n3", Extensions: []string{"n3"}},
	{Type: "text/plain", Extensions: []string{"txt", "text", "conf", "def", "list", "log", "in"}},
	{Type: "text/prs.lines.tag", Extensions: []string{"dsc"}},
	{Type: "text/richtext", Extensions: []string{"rtx"}},
	{Type: "text/sgml", Extensions: []string{"sgml", "sgm"}},
	{Type: "text/tab-separated-values", Extensions: []string{"tsv"}},
	{Type: "text/troff", Extensions: []string{"t", "tr", "roff", "man", "me", "ms"}},
	{Type: "text/turtle", Extensions: []string{"ttl"}},
	{Type: "text/uri-list", Extensions: []string{"uri", "uris", "urls"}},
	{Type: "text/vcard", Extensions: []string{"vcard"}},
	{Type: "text/vnd.curl", Extensions: []string{"curl"}},
	{Type: "text/vnd.curl.dcurl", Extensions: []string{"dcurl"}},
	{Type: "text/vnd.curl.scurl", Extensions: []string{"scurl"}},
	{Type: "text/vnd.curl.mcurl", Extensions: []string{"mcurl"}},
	{Type: "text/vnd.dvb.subtitle", Extensions: []string{"sub"}},
	{Type: "text/vnd.fly", Extensions: []string{"fly"}},
	{Type: "text/vnd.fmi.flexstor", Extensions: []string{"flx"}},
	{Type: "text/vnd.graphviz", Extensions: []string{"gv"}},
	{Type: "text/vnd.in3d.3dml", Extensions: []string{"3dml"}},
	{Type: "text/vnd.in3d.spot", Extensions: []string{"spot"}},
	{Type: "text/vnd.sun.j2me.app-descriptor", Extensions: []string{"jad"}},
	{Type: "text/vnd.wap.wml", Extensions: []string{"wml"}},
	{Type: "text/vnd.wap.wmlscript", Extensions: []string{"wmls"}},
	{Type: "text/x-asm", Extensions: []string{"s", "asm"}},
	{Type: "text/x-fortran", Extensions: []string{"f", "for", "f77", "f90"}},
	{Type: "text/x-java-source", Extensions: []string{"java"}},
	{Type: "text/x-opml", Extensions: []string{"opml"}},
	{Type: "text/x-pascal", Extensions: []string{"p", "pas"}},
	{Type: "text/x-nfo", Extensions: []string{"nfo"}},
	{Type: "text/x-setext", Extensions: []string{"etx"}},
	{Type: "text/x-sfv", Extensions: []string{"sfv"}},
	{Type: "text/x-uuencode", Extensions: []string{"uu"}},
	{Type: "text/x-vcalendar", Extensions: []string{"vcs"}},
	{Type: "text/x-vcard", Extensions: []string{"vcf"}},
	{Type: "video/3gpp", Extensions: []string{"3gp"}},
	{Type: "video/3gpp2", Extensions: []string{"3g2"}},
	{Type: "video/h261", Extensions: []string{"h261"}},
	{Type: "video/h263", Extensions: []string{"h263"}},
	{Type: "video/h264", Extensions: []string{"h264"}},
	{Type: "video/jpeg", Extensions: []string{"jpgv"}},
	{Type: "video/jpm", Extensions: []string{"jpm", "jpgm"}},
	{Type: "video/mj2", Extensions: []string{"mj2"}},
	{Type: "video/mp4", Extensions: []string{"mp4"}},
	{Type: "video/mpeg", Extensions: []string{"mpeg", "mpg", "mpe", "m1v", "m2v"}},
	{Type: "video/ogg", Extensions: []string{"ogv"}},
	{Type: "video/quicktime", Extensions: []string{"qt", "mov"}},
	{Type: "video/vnd.dece.hd", Extensions: []string{"uvh", "uvvh"}},
	{Type: "video/vnd.dece.mobile", Extensions: []string{"uvm", "uvvm"}},
	{Type: "video/vnd.dece.pd", Extensions: []string{"uvp", "uvvp"}},
	{Type: "video/vnd.dece.sd", Extensions: []string{"uvs", "uvvs"}},
	{Type: "video/vnd.dece.video", Extensions: []string{"uvv", "uvvv"}},
	{Type: "video/vnd.dvb.file", Extensions: []string{"dvb"}},
	{Type: "video/vnd.fvt", Extensions: []string{"fvt"}},
	{Type: "video/vnd.mpegurl", Extensions: []string{"mxu", "m4u"}},
	{Type: "video/vnd.ms-playready.media.pyv", Extensions: []string{"pyv"}},
	{Type: "video/vnd.uvvu.mp4", Extensions: []string{"uvu", "uvvu"}},
	{Type: "video/vnd.vivo", Extensions: []string{"viv"}},
	{Type: "video/webm", Extensions: []string{"webm"}},
	{Type: "video/x-f4v", Extensions: []string{"f4v"}},
	{Type: "video/x-fli", Extensions: []string{"fli"}},
	{Type: "video/x-flv", Extensions: []string{"flv"}},
	{Type: "video/x-m4v", Extensions: []string{"m4v"}},
	{Type: "video/x-matroska", Extensions: []string{"mkv", "mk3d", "mks"}},
	{Type: "video/x-mng", Extensions: []string{"mng"}},
	{Type: "video/x-ms-asf", Extensions: []string{"asf", "asx"}},
	{Type: "video/x-ms-vob", Extensions: []string{"vob"}},
	{Type: "video/x-ms-wm", Extensions: []string{"wm"}},
	{Type: "video/x-ms-wmv", Extensions: []string{"wmv"}},
	{Type: "video/x-ms-wmx", Extensions: []string{"wmx"}},
	{Type: "video/x-ms-wvx", Extensions: []string{"wvx"}},
	{Type: "video/x-msvideo", Extensions: []string{"avi"}},
	{Type: "video/x-sgi-movie", Extensions: []string{"movie"}},
}
